### ISSUE TITLE
[flatpak] Crash when opening the settings 

### ISSUE THREAD

**Issue by Ferenc-** [Tubefeeder/Tubefeeder#108]
The current latest flatpak from flathub crashes immediately after opening the settings.

````
thread 'main' panicked at 'Settings entry to have parent of thpe ActionRow: Widget { inner: ObjectRef { inner: 0x55a1afab8c30, type: GtkBox } }', src/g
ui/preferences_window.rs:73:22                                                                                                                         
stack backtrace:                                                                                                                                       
   0:     0x55a1ac974c7d - std::backtrace_rs::backtrace::libunwind::trace::h9135f25bc195152c                                                           
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5      
   1:     0x55a1ac974c7d - std::backtrace_rs::backtrace::trace_unsynchronized::h015ee85be510df51                                                       
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5            
   2:     0x55a1ac974c7d - std::sys_common::backtrace::_print_fmt::h5fad03caa9652a2c                                                                   
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:66:5                         
   3:     0x55a1ac974c7d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2b42ca28d244e5c7                        
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:45:22                        
   4:     0x55a1ac99b48c - core::fmt::write::h401e827d053130ed                                                                                         
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/fmt/mod.rs:1198:17                                  
   5:     0x55a1ac96ed01 - std::io::Write::write_fmt::hffec93268f5cde32                                                                                
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/io/mod.rs:1672:15                                    
   6:     0x55a1ac976475 - std::sys_common::backtrace::_print::h180c4c706ee1d3fb                                                                       
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:48:5                         
   7:     0x55a1ac976475 - std::sys_common::backtrace::print::hd0c35d18765761c9                                                                        
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:35:9                         
   8:     0x55a1ac976475 - std::panicking::default_hook::{{closure}}::h1f023310983bc730                                                                
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:295:22                                  
   9:     0x55a1ac976191 - std::panicking::default_hook::h188fec3334afd5be                                                                             
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:314:9                                   
  10:     0x55a1ac976a06 - std::panicking::rust_panic_with_hook::hf26e9d4f97b40096                                                                     
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:698:17                                  
  11:     0x55a1ac9768f7 - std::panicking::begin_panic_handler::{{closure}}::hfab912107608087a                                                         
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:588:13                                  
  12:     0x55a1ac975174 - std::sys_common::backtrace::__rust_end_short_backtrace::h434b685ce8d9965b                                                   
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:138:18                       
  13:     0x55a1ac976629 - rust_begin_unwind                                                                                                           
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5                                   
  14:     0x55a1ac404223 - core::panicking::panic_fmt::ha6dc7f2ab2479463                                                                               
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14                                 
  15:     0x55a1ac404373 - core::result::unwrap_failed::h42ad8e915aa0a906                                                                              
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/result.rs:1814:5                                    
  16:     0x55a1ac461ccc - tubefeeder::gui::preferences_window::imp::PreferencesWindow::init_string_setting::h5ac99cc41a85580e                         
  17:     0x55a1ac45ff6b - <tubefeeder::gui::preferences_window::imp::PreferencesWindow as glib::subclass::object::ObjectImpl>::constructed::hedea861ccbaf3ade
    18:     0x55a1ac447b42 - glib::subclass::object::constructed::h0cdf5acba15291e8                                                            [42/46583]
  19:     0x7fae4d21e872 - <unknown>                                                                                                                   
  20:     0x7fae4d220210 - g_object_newv                         
  21:     0x55a1ac94b990 - glib::object::Object::new_internal::h8a29d7086ceaa152                                                                       
  22:     0x55a1ac94b45b - glib::object::Object::with_type::hef5907277aad01d9
  23:     0x55a1ac4aeffd - glib::object::Object::new::haec063cbff01cc12                                                                                
  24:     0x55a1ac44d4e7 - gio::auto::simple_action::SimpleAction::connect_activate::activate_trampoline::h5ee516b7042eb103                            
  25:     0x7fae4d2184f2 - g_closure_invoke                                                                                                            
  26:     0x7fae4d22d1e8 - <unknown>                                       
  27:     0x7fae4d234155 - g_signal_emit_valist                                                                                                        
  28:     0x7fae4d234323 - g_signal_emit                                                                                                               
  29:     0x7fae4d3681fd - <unknown>                                                                                                                   
  30:     0x7fae4d9fde37 - <unknown>                                                                                                                   
  31:     0x7fae4d9f9b28 - <unknown>                                                                                                                   
  32:     0x7fae4d2184f2 - g_closure_invoke                                
  33:     0x7fae4d22d1e8 - <unknown>                                                                                                                   
  34:     0x7fae4d234155 - g_signal_emit_valist                                                                                                        
  35:     0x7fae4d234323 - g_signal_emit                                                                                                               
  36:     0x7fae4d70fab3 - <unknown>                                                                                                                   
  37:     0x7fae4d21870a - <unknown>                                       
  38:     0x7fae4d23411f - g_signal_emit_valist                                                                                                        
  39:     0x7fae4d234323 - g_signal_emit                         
  40:     0x7fae4d7f6363 - <unknown>                                                                                                                   
  41:     0x7fae4d21b9ca - g_cclosure_marshal_VOID__BOXEDv
  42:     0x7fae4d21870a - <unknown>
  43:     0x7fae4d23411f - g_signal_emit_valist
  44:     0x7fae4d234323 - g_signal_emit
  45:     0x7fae4d7f2908 - <unknown>
  46:     0x7fae4d7f438b - <unknown>
  47:     0x7fae4d7f7a37 - <unknown>
  48:     0x7fae4d7bf17f - <unknown>
  49:     0x7fae4d97ae2a - <unknown>
  50:     0x7fae4d9831f8 - <unknown>
  51:     0x7fae4d848752 - <unknown>
  52:     0x7fae4d848e3b - <unknown>
  53:     0x7fae4d87a990 - <unknown>
  54:     0x7fae4da8f3dc - <unknown>
  55:     0x7fae4dabc1e8 - <unknown>
  56:     0x7fae4d21870a - <unknown>                                                                                                                   
  57:     0x7fae4d23355e - g_signal_emit_valist
  58:     0x7fae4d234323 - g_signal_emit
  59:     0x7fae4dabfed0 - <unknown>
  60:     0x7fae4dae0746 - <unknown>
  61:     0x7fae4d11b681 - g_main_context_dispatch
  62:     0x7fae4d11bbd8 - <unknown>
  63:     0x7fae4d11bc73 - g_main_context_iteration
  64:     0x7fae4d35ebad - g_application_run
  65:     0x55a1ac424b6a - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h040175514f9b836c
  66:     0x55a1ac49403a - std::thread::local::LocalKey<T>::with::h521cb21e50376cde
  67:     0x55a1ac4a5e4a - tokio::park::thread::CachedParkThread::block_on::hba6023d37f0ccf68
  68:     0x55a1ac46a5dc - tokio::runtime::thread_pool::ThreadPool::block_on::h5644f5693072bca3
  69:     0x55a1ac45992e - tokio::runtime::Runtime::block_on::h4f082d79931944e6
  70:     0x55a1ac44cf69 - tubefeeder::main::h681e50decdc97cf7
  71:     0x55a1ac49f673 - std::sys_common::backtrace::__rust_begin_short_backtrace::h87d3dd4c2c96a421
  72:     0x55a1ac42ac59 - std::rt::lang_start::{{closure}}::h7be9cfd98fef3f46
  73:     0x55a1ac9692fe - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hcdfee62722e5e4b8
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:280:13
  74:     0x55a1ac9692fe - std::panicking::try::do_call::h84ca51609826746f
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:492:40
  75:     0x55a1ac9692fe - std::panicking::try::hd58075e533b8e0cb
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:456:19
  76:     0x55a1ac9692fe - std::panic::catch_unwind::h1ebac24d83cb6ce2
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panic.rs:137:14
  77:     0x55a1ac9692fe - std::rt::lang_start_internal::{{closure}}::h0145388a1edd1640
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/rt.rs:128:48
  78:     0x55a1ac9692fe - std::panicking::try::do_call::h7630182e534a0a32
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:492:40
  79:     0x55a1ac9692fe - std::panicking::try::h05b6544f0c6331dc
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:456:19
  80:     0x55a1ac9692fe - std::panic::catch_unwind::h77b2ba8fd3309f34
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panic.rs:137:14
  81:     0x55a1ac9692fe - std::rt::lang_start_internal::h6612c8a7a6861b8b
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/rt.rs:128:20
  82:     0x55a1ac44d022 - main
  83:     0x7fae4c8d754a - <unknown>
  84:     0x7fae4c8d760b - __libc_start_main
  85:     0x55a1ac404525 - _start
                               at /buildstream/freedesktop-sdk/bootstrap/glibc.bst/csu/../sysdeps/x86_64/start.S:115
  86:                0x0 - <unknown>

  
````

**Comment by Schmiddiii** [comment]
I can actually reproduce it. You have one of the `PLAYER` or `DOWNLOADER` or `PIPED_API_URL` environmental variables set. If you unset them, it should not crash. I will try to fix it such that it will also work with those environmental variables.
